# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6193c563cca6a63c9a18247e92cec0df5699f8734bbda39cffe1545bd78af3e51a8998be19a955838dc1f3cb883ff9e1303a6bd7be9c2085bcca25495e79a6a9

test:
  secret_key_base: 114ace72b6032465fa25b8ab0c67b07d8dbf5fd57d0eb4510b8b87ec20dc244f4e081cbbd858eb07c6678d635e6a0036d65b9a791edc7161c1f63e623c156af3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
